(cl:defpackage carpet_detect_msgs-msg
  (:use )
  (:export
   "<CAMERACOORDINATE>"
   "CAMERACOORDINATE"
   "<OBJECTCAMERADETECTRESULT>"
   "OBJECTCAMERADETECTRESULT"
   "<OBJECTCAMERADETECTRESULTARRAY>"
   "OBJECTCAMERADETECTRESULTARRAY"
  ))

