# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from carpet_detect_msgs/ObjectCameraDetectResult.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import carpet_detect_msgs.msg

class ObjectCameraDetectResult(genpy.Message):
  _md5sum = "3d362a9701db027a22375f917c033511"
  _type = "carpet_detect_msgs/ObjectCameraDetectResult"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 prop
int32 cls_id
CameraCoordinate[24] coords
================================================================================
MSG: carpet_detect_msgs/CameraCoordinate
float32 x
float32 y
float32 z
"""
  __slots__ = ['prop','cls_id','coords']
  _slot_types = ['float32','int32','carpet_detect_msgs/CameraCoordinate[24]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       prop,cls_id,coords

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObjectCameraDetectResult, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.prop is None:
        self.prop = 0.
      if self.cls_id is None:
        self.cls_id = 0
      if self.coords is None:
        self.coords = [carpet_detect_msgs.msg.CameraCoordinate() for _ in range(24)]
    else:
      self.prop = 0.
      self.cls_id = 0
      self.coords = [carpet_detect_msgs.msg.CameraCoordinate() for _ in range(24)]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_fi().pack(_x.prop, _x.cls_id))
      if len(self.coords) != 24:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (24, len(self.coords), 'self.coords')))
      for val1 in self.coords:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.coords is None:
        self.coords = None
      end = 0
      _x = self
      start = end
      end += 8
      (_x.prop, _x.cls_id,) = _get_struct_fi().unpack(str[start:end])
      self.coords = []
      for i in range(0, 24):
        val1 = carpet_detect_msgs.msg.CameraCoordinate()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.coords.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_fi().pack(_x.prop, _x.cls_id))
      if len(self.coords) != 24:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (24, len(self.coords), 'self.coords')))
      for val1 in self.coords:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.coords is None:
        self.coords = None
      end = 0
      _x = self
      start = end
      end += 8
      (_x.prop, _x.cls_id,) = _get_struct_fi().unpack(str[start:end])
      self.coords = []
      for i in range(0, 24):
        val1 = carpet_detect_msgs.msg.CameraCoordinate()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.coords.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_fi = None
def _get_struct_fi():
    global _struct_fi
    if _struct_fi is None:
        _struct_fi = struct.Struct("<fi")
    return _struct_fi
