// Generated by gencpp from file carpet_detect_msgs/CameraCoordinate.msg
// DO NOT EDIT!


#ifndef CARPET_DETECT_MSGS_MESSAGE_CAMERACOORDINATE_H
#define CARPET_DETECT_MSGS_MESSAGE_CAMERACOORDINATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace carpet_detect_msgs
{
template <class ContainerAllocator>
struct CameraCoordinate_
{
  typedef CameraCoordinate_<ContainerAllocator> Type;

  CameraCoordinate_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  CameraCoordinate_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> const> ConstPtr;

}; // struct CameraCoordinate_

typedef ::carpet_detect_msgs::CameraCoordinate_<std::allocator<void> > CameraCoordinate;

typedef boost::shared_ptr< ::carpet_detect_msgs::CameraCoordinate > CameraCoordinatePtr;
typedef boost::shared_ptr< ::carpet_detect_msgs::CameraCoordinate const> CameraCoordinateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator1> & lhs, const ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator1> & lhs, const ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carpet_detect_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc153912f1453b70ULL;
  static const uint64_t static_value2 = 0x8d221682bc23d9acULL;
};

template<class ContainerAllocator>
struct DataType< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carpet_detect_msgs/CameraCoordinate";
  }

  static const char* value(const ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraCoordinate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARPET_DETECT_MSGS_MESSAGE_CAMERACOORDINATE_H
