// Generated by gencpp from file carpet_detect_msgs/ObjectCameraDetectResult.msg
// DO NOT EDIT!


#ifndef CARPET_DETECT_MSGS_MESSAGE_OBJECTCAMERADETECTRESULT_H
#define CARPET_DETECT_MSGS_MESSAGE_OBJECTCAMERADETECTRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <carpet_detect_msgs/CameraCoordinate.h>

namespace carpet_detect_msgs
{
template <class ContainerAllocator>
struct ObjectCameraDetectResult_
{
  typedef ObjectCameraDetectResult_<ContainerAllocator> Type;

  ObjectCameraDetectResult_()
    : prop(0.0)
    , cls_id(0)
    , coords()  {
    }
  ObjectCameraDetectResult_(const ContainerAllocator& _alloc)
    : prop(0.0)
    , cls_id(0)
    , coords()  {
  (void)_alloc;
      coords.assign( ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> (_alloc));
  }



   typedef float _prop_type;
  _prop_type prop;

   typedef int32_t _cls_id_type;
  _cls_id_type cls_id;

   typedef boost::array< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> , 24>  _coords_type;
  _coords_type coords;





  typedef boost::shared_ptr< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectCameraDetectResult_

typedef ::carpet_detect_msgs::ObjectCameraDetectResult_<std::allocator<void> > ObjectCameraDetectResult;

typedef boost::shared_ptr< ::carpet_detect_msgs::ObjectCameraDetectResult > ObjectCameraDetectResultPtr;
typedef boost::shared_ptr< ::carpet_detect_msgs::ObjectCameraDetectResult const> ObjectCameraDetectResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator1> & lhs, const ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator2> & rhs)
{
  return lhs.prop == rhs.prop &&
    lhs.cls_id == rhs.cls_id &&
    lhs.coords == rhs.coords;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator1> & lhs, const ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carpet_detect_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d362a9701db027a22375f917c033511";
  }

  static const char* value(const ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d362a9701db027aULL;
  static const uint64_t static_value2 = 0x22375f917c033511ULL;
};

template<class ContainerAllocator>
struct DataType< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carpet_detect_msgs/ObjectCameraDetectResult";
  }

  static const char* value(const ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 prop\n"
"int32 cls_id\n"
"CameraCoordinate[24] coords\n"
"================================================================================\n"
"MSG: carpet_detect_msgs/CameraCoordinate\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.prop);
      stream.next(m.cls_id);
      stream.next(m.coords);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectCameraDetectResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "prop: ";
    Printer<float>::stream(s, indent + "  ", v.prop);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cls_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cls_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "coords: ";
    if (v.coords.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.coords.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::carpet_detect_msgs::CameraCoordinate_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.coords[i]);
    }
    if (v.coords.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARPET_DETECT_MSGS_MESSAGE_OBJECTCAMERADETECTRESULT_H
