// Generated by gencpp from file carpet_detect_msgs/ObjectCameraDetectResultArray.msg
// DO NOT EDIT!


#ifndef CARPET_DETECT_MSGS_MESSAGE_OBJECTCAMERADETECTRESULTARRAY_H
#define CARPET_DETECT_MSGS_MESSAGE_OBJECTCAMERADETECTRESULTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <carpet_detect_msgs/ObjectCameraDetectResult.h>

namespace carpet_detect_msgs
{
template <class ContainerAllocator>
struct ObjectCameraDetectResultArray_
{
  typedef ObjectCameraDetectResultArray_<ContainerAllocator> Type;

  ObjectCameraDetectResultArray_()
    : header()
    , results()  {
    }
  ObjectCameraDetectResultArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , results(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> >> _results_type;
  _results_type results;





  typedef boost::shared_ptr< ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectCameraDetectResultArray_

typedef ::carpet_detect_msgs::ObjectCameraDetectResultArray_<std::allocator<void> > ObjectCameraDetectResultArray;

typedef boost::shared_ptr< ::carpet_detect_msgs::ObjectCameraDetectResultArray > ObjectCameraDetectResultArrayPtr;
typedef boost::shared_ptr< ::carpet_detect_msgs::ObjectCameraDetectResultArray const> ObjectCameraDetectResultArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator1> & lhs, const ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.results == rhs.results;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator1> & lhs, const ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carpet_detect_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "144956ded8fbb06613a9be71d49669f9";
  }

  static const char* value(const ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x144956ded8fbb066ULL;
  static const uint64_t static_value2 = 0x13a9be71d49669f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carpet_detect_msgs/ObjectCameraDetectResultArray";
  }

  static const char* value(const ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"ObjectCameraDetectResult[] results\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: carpet_detect_msgs/ObjectCameraDetectResult\n"
"float32 prop\n"
"int32 cls_id\n"
"CameraCoordinate[24] coords\n"
"================================================================================\n"
"MSG: carpet_detect_msgs/CameraCoordinate\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.results);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectCameraDetectResultArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carpet_detect_msgs::ObjectCameraDetectResultArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "results: ";
    if (v.results.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.results.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::carpet_detect_msgs::ObjectCameraDetectResult_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.results[i]);
    }
    if (v.results.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARPET_DETECT_MSGS_MESSAGE_OBJECTCAMERADETECTRESULTARRAY_H
